#!/usr/bin/env bash
# lsp-doctor.sh — Diagnose and install LSP servers + Claude Code/Codex MCP wiring + project dependencies
# Usage: bash lsp-doctor.sh [--fix] [--project-dir <path>] [--codex-lsp-only]
# Without --fix: report only. With --fix: auto-install missing components.
set -euo pipefail

FIX=false
CODEX_LSP_ONLY=false
PROJECT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
REPORT=""
FIXED=""
MISSING=""
CLAUDE_SETTINGS="$HOME/.claude/settings.json"
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
CODEX_CONFIG="$CODEX_HOME/config.toml"
LSP_MCP_DIR="$CODEX_HOME/tools/lsp-mcp"
LSP_MCP_BIN="$LSP_MCP_DIR/target/release/lsp-mcp"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LSP_MCP_PATCH="$SCRIPT_DIR/../patches/lsp-mcp-codex-compat.patch"

while [[ $# -gt 0 ]]; do
  case $1 in
    --fix) FIX=true; shift ;;
    --project-dir) PROJECT_DIR="$2"; shift 2 ;;
    --codex-lsp-only) CODEX_LSP_ONLY=true; shift ;;
    *) shift ;;
  esac
done

log() { REPORT+="$1"$'\n'; }
ok()  { log "  [OK] $1"; }
miss(){ log "  [MISSING] $1"; MISSING+="$1"$'\n'; }
fix() { log "  [FIXED] $1"; FIXED+="$1"$'\n'; }

git_tracked() {
  git ls-files --error-unmatch "$1" >/dev/null 2>&1
}

git_ignored() {
  git check-ignore -q "$1" >/dev/null 2>&1
}

ensure_git_info_exclude() {
  local patterns=("$@")
  if ! git rev-parse --git-dir >/dev/null 2>&1; then
    ok "not a git repo; skip .git/info/exclude"
    return
  fi

  local exclude_path
  exclude_path="$(git rev-parse --git-path info/exclude)"
  mkdir -p "$(dirname "$exclude_path")"
  [ -f "$exclude_path" ] || : > "$exclude_path"

  local missing=()
  local pattern
  for pattern in "${patterns[@]}"; do
    grep -qxF "$pattern" "$exclude_path" 2>/dev/null || missing+=("$pattern")
  done

  if [ ${#missing[@]} -eq 0 ]; then
    ok ".git/info/exclude has local code intelligence ignores"
    return
  fi

  miss ".git/info/exclude missing: ${missing[*]}"
  if $FIX; then
    {
      echo ""
      echo "# Local code intelligence (generated by code-map skill)"
      printf "%s\n" "${missing[@]}"
    } >> "$exclude_path"
    fix ".git/info/exclude updated"
  fi
}

json_languages() {
  local langs=()
  $HAS_TS && langs+=("typescript")
  $HAS_GO && langs+=("golang")
  $HAS_PY && langs+=("python")
  $HAS_RUST && langs+=("rust")
  python3 - "${langs[@]}" <<'PY'
import json, sys
print(json.dumps(sys.argv[1:]))
PY
}

update_codex_lsp_config() {
  local config_path="$1"
  local command_path="$2"
  mkdir -p "$(dirname "$config_path")"
  [ -f "$config_path" ] || : > "$config_path"
  python3 - "$config_path" "$command_path" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
command = sys.argv[2]
lines = path.read_text().splitlines()
out = []
i = 0
while i < len(lines):
    line = lines[i].strip()
    if line == "[mcp_servers.lsp-mcp]":
        i += 1
        while i < len(lines) and not (lines[i].startswith("[") and lines[i].endswith("]")):
            i += 1
        continue
    out.append(lines[i])
    i += 1

while out and not out[-1].strip():
    out.pop()

if out:
    out.append("")
out.extend([
    "[mcp_servers.lsp-mcp]",
    f'command = "{command}"',
    "enabled = true",
])
path.write_text("\n".join(out) + "\n")
PY
}

update_codex_codegraph_config() {
  local config_path="$1"
  mkdir -p "$(dirname "$config_path")"
  [ -f "$config_path" ] || : > "$config_path"
  python3 - "$config_path" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
lines = path.read_text().splitlines()
out = []
i = 0
while i < len(lines):
    line = lines[i].strip()
    if line == "[mcp_servers.codegraph]":
        i += 1
        while i < len(lines) and not (lines[i].startswith("[") and lines[i].endswith("]")):
            i += 1
        continue
    out.append(lines[i])
    i += 1

while out and not out[-1].strip():
    out.pop()

if out:
    out.append("")
out.extend([
    "[mcp_servers.codegraph]",
    'command = "npx"',
    'args = ["-y", "@colbymchenry/codegraph", "serve", "--mcp"]',
    "enabled = true",
])
path.write_text("\n".join(out) + "\n")
PY
}

write_project_lsp_config() {
  local config_path="$1"
  local languages_json="$2"
  python3 - "$config_path" "$languages_json" <<'PY'
from pathlib import Path
import json, sys

path = Path(sys.argv[1])
languages = json.loads(sys.argv[2])
config = {
    "languages": languages,
    "tools": {
        "preset": "minimal",
        "enable": ["documentSymbol"],
        "initial_setup": "disabled",
    },
}
path.write_text(json.dumps(config, indent=2, ensure_ascii=False) + "\n")
PY
}

remove_legacy_project_lsp_mcp_config() {
  local config_path="$1"
  python3 - "$config_path" <<'PY'
from pathlib import Path
import json, sys

path = Path(sys.argv[1])
data = json.loads(path.read_text())
servers = data.get("mcpServers")
if isinstance(servers, dict) and "lsp-mcp" in servers:
    del servers["lsp-mcp"]
path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")
PY
}

apply_lsp_mcp_patch_if_present() {
  [ -f "$LSP_MCP_PATCH" ] || return 0
  [ -d "$LSP_MCP_DIR/.git" ] || return 0

  if git -C "$LSP_MCP_DIR" apply --reverse --check "$LSP_MCP_PATCH" >/dev/null 2>&1; then
    ok "Codex lsp-mcp compatibility patch already applied"
    return 0
  fi
  if git -C "$LSP_MCP_DIR" apply --check "$LSP_MCP_PATCH" >/dev/null 2>&1; then
    git -C "$LSP_MCP_DIR" apply "$LSP_MCP_PATCH"
    fix "Codex lsp-mcp compatibility patch applied"
  else
    miss "Codex lsp-mcp compatibility patch could not be applied cleanly"
  fi
}

build_lsp_mcp_release() {
  local build_log
  build_log="$(mktemp)"

  if (
    cd "$LSP_MCP_DIR"
    if [ ! -f Cargo.lock ]; then
      cargo generate-lockfile
    fi
    cargo build --release --locked
  ) >"$build_log" 2>&1; then
    tail -8 "$build_log"
    rm -f "$build_log"
    return 0
  fi

  tail -20 "$build_log"
  rm -f "$build_log"
  return 1
}

cd "$PROJECT_DIR"
PROJECT_DIR="$(pwd)"

HAS_TS=false; HAS_GO=false; HAS_PY=false; HAS_RUST=false
if [ -f tsconfig.json ] || [ -f package.json ]; then HAS_TS=true; fi
if [ -f go.mod ]; then HAS_GO=true; fi
if [ -f pyproject.toml ] || [ -f setup.py ] || [ -f requirements.txt ]; then HAS_PY=true; fi
if [ -f Cargo.toml ]; then HAS_RUST=true; fi

# --- Phase 0: Claude Code LSP Plugin ---
if ! $CODEX_LSP_ONLY; then
log "=== Claude Code LSP Plugin ==="

# Check ENABLE_LSP_TOOL
if [ -f "$CLAUDE_SETTINGS" ] && grep -q '"ENABLE_LSP_TOOL"' "$CLAUDE_SETTINGS" 2>/dev/null; then
  ok "ENABLE_LSP_TOOL is set"
else
  miss "ENABLE_LSP_TOOL not set in ~/.claude/settings.json"
  if $FIX; then
    if [ -f "$CLAUDE_SETTINGS" ]; then
      # Add env.ENABLE_LSP_TOOL to existing settings
      python3 -c "
import json, sys
with open('$CLAUDE_SETTINGS') as f: d = json.load(f)
d.setdefault('env', {})['ENABLE_LSP_TOOL'] = '1'
with open('$CLAUDE_SETTINGS', 'w') as f: json.dump(d, f, indent=2)
print('  Added ENABLE_LSP_TOOL=1')
" 2>&1
    else
      mkdir -p "$(dirname "$CLAUDE_SETTINGS")"
      echo '{"env":{"ENABLE_LSP_TOOL":"1"}}' > "$CLAUDE_SETTINGS"
    fi
    fix "ENABLE_LSP_TOOL enabled"
  fi
fi

# Check marketplace registration
if [ -f "$CLAUDE_SETTINGS" ] && grep -q 'claude-code-lsps' "$CLAUDE_SETTINGS" 2>/dev/null; then
  ok "Piebald-AI/claude-code-lsps marketplace registered"
else
  miss "claude-code-lsps marketplace not registered"
  if $FIX; then
    python3 -c "
import json
with open('$CLAUDE_SETTINGS') as f: d = json.load(f)
d.setdefault('extraKnownMarketplaces', {})['claude-code-lsps'] = {
  'source': {'source': 'github', 'repo': 'Piebald-AI/claude-code-lsps'}
}
with open('$CLAUDE_SETTINGS', 'w') as f: json.dump(d, f, indent=2)
print('  Registered claude-code-lsps marketplace')
" 2>&1
    fix "marketplace registered"
  fi
fi

# Check enabled plugins
check_plugin() {
  local plugin="$1"
  if [ -f "$CLAUDE_SETTINGS" ] && grep -q "\"${plugin}@claude-code-lsps\"" "$CLAUDE_SETTINGS" 2>/dev/null; then
    ok "plugin ${plugin}@claude-code-lsps enabled"
  else
    miss "plugin ${plugin}@claude-code-lsps not enabled"
    if $FIX; then
      python3 -c "
import json
with open('$CLAUDE_SETTINGS') as f: d = json.load(f)
d.setdefault('enabledPlugins', {})['${plugin}@claude-code-lsps'] = True
with open('$CLAUDE_SETTINGS', 'w') as f: json.dump(d, f, indent=2)
print('  Enabled ${plugin}@claude-code-lsps')
" 2>&1
      fix "plugin ${plugin} enabled"
    fi
  fi
}

$HAS_TS && check_plugin "vtsls"
$HAS_GO && check_plugin "gopls"
$HAS_PY && check_plugin "pyright"
$HAS_RUST && check_plugin "rust-analyzer"
else
log "=== Claude Code LSP Plugin ==="
ok "skipped (--codex-lsp-only)"
fi

# --- Phase 1: System-level LSP servers ---
log ""
log "=== LSP Server Binaries ==="

# TypeScript (vtsls is the preferred server for Claude Code plugin)
if $HAS_TS; then
  if command -v vtsls &>/dev/null; then
    ok "vtsls $(vtsls --version 2>&1 | head -1)"
  elif command -v typescript-language-server &>/dev/null; then
    ok "typescript-language-server (fallback) $(typescript-language-server --version 2>&1 | head -1)"
  else
    miss "vtsls (needed for TS/JS LSP in Claude Code)"
    if $FIX; then
      npm install -g @vtsls/language-server 2>&1 | tail -1
      fix "vtsls installed"
    fi
  fi
fi

# Go
if $HAS_GO; then
  if command -v gopls &>/dev/null; then
    ok "gopls $(gopls version 2>&1 | head -1)"
  else
    miss "gopls (needed for Go LSP)"
    if $FIX; then
      go install golang.org/x/tools/gopls@latest 2>&1 | tail -1
      fix "gopls installed"
    fi
  fi
fi

# Python
if $HAS_PY; then
  if command -v pyright-langserver &>/dev/null || command -v pyright &>/dev/null; then
    ok "pyright"
  else
    miss "pyright (needed for Python LSP)"
    if $FIX; then
      pip3 install pyright 2>&1 | tail -1
      fix "pyright installed"
    fi
  fi
fi

# Rust
if $HAS_RUST; then
  if command -v rust-analyzer &>/dev/null; then
    ok "rust-analyzer"
  else
    miss "rust-analyzer (needed for Rust LSP)"
    if $FIX; then
      rustup component add rust-analyzer 2>&1 | tail -1
      fix "rust-analyzer installed"
    fi
  fi
fi

# --- Phase 2: Codex LSP MCP ---
log ""
log "=== Codex LSP MCP ==="

if [ -x "$LSP_MCP_BIN" ]; then
  ok "lsp-mcp binary exists at $LSP_MCP_BIN"
elif command -v lsp-mcp &>/dev/null; then
  ok "lsp-mcp found on PATH: $(command -v lsp-mcp)"
else
  miss "lsp-mcp binary not found for Codex"
  if $FIX; then
    command -v cargo >/dev/null || { miss "cargo not found (needed to build lsp-mcp)"; }
    command -v git >/dev/null || { miss "git not found (needed to fetch lsp-mcp)"; }
    if command -v cargo >/dev/null && command -v git >/dev/null; then
      mkdir -p "$CODEX_HOME/tools"
      if [ ! -d "$LSP_MCP_DIR/.git" ]; then
        git clone https://github.com/BumpyClock/lsp-mcp.git "$LSP_MCP_DIR" 2>&1 | tail -3
        fix "lsp-mcp source cloned"
      fi
      apply_lsp_mcp_patch_if_present
      if build_lsp_mcp_release && [ -x "$LSP_MCP_BIN" ]; then
        fix "lsp-mcp release binary built"
      else
        miss "lsp-mcp build did not produce $LSP_MCP_BIN"
      fi
    fi
  fi
fi

if [ -f "$CODEX_CONFIG" ] && grep -q '^\[mcp_servers\.lsp-mcp\]' "$CODEX_CONFIG" 2>/dev/null; then
  ok "$CODEX_CONFIG has lsp-mcp MCP server"
else
  miss "$CODEX_CONFIG missing lsp-mcp MCP server"
  if $FIX; then
    if [ -x "$LSP_MCP_BIN" ]; then
      update_codex_lsp_config "$CODEX_CONFIG" "$LSP_MCP_BIN"
      fix "Codex lsp-mcp MCP server registered"
    elif command -v lsp-mcp &>/dev/null; then
      update_codex_lsp_config "$CODEX_CONFIG" "$(command -v lsp-mcp)"
      fix "Codex lsp-mcp MCP server registered"
    else
      miss "cannot register Codex lsp-mcp before binary exists"
    fi
  fi
fi

if [ -f "$LSP_MCP_PATCH" ] && [ -d "$LSP_MCP_DIR/.git" ]; then
  if git -C "$LSP_MCP_DIR" apply --reverse --check "$LSP_MCP_PATCH" >/dev/null 2>&1; then
    ok "Codex lsp-mcp compatibility patch already applied"
  else
    miss "Codex lsp-mcp compatibility patch not applied"
    if $FIX; then
      apply_lsp_mcp_patch_if_present
      if build_lsp_mcp_release && [ -x "$LSP_MCP_BIN" ]; then
        fix "lsp-mcp release binary rebuilt after compatibility patch"
      else
        miss "lsp-mcp rebuild did not produce $LSP_MCP_BIN"
      fi
    fi
  fi
fi

if [ -f .lsp-mcp.json ]; then
  ok ".lsp-mcp.json exists"
else
  miss ".lsp-mcp.json not found"
  if $FIX; then
    write_project_lsp_config ".lsp-mcp.json" "$(json_languages)"
    fix ".lsp-mcp.json created"
  fi
fi

ensure_git_info_exclude \
  ".lsp-mcp/" \
  ".lsp-mcp.json" \
  ".codex/" \
  ".claude/" \
  ".agents/" \
  "CLAUDE.md" \
  "AGENTS.md"

if ! $CODEX_LSP_ONLY; then
# --- Phase 3: Project dependencies ---
log ""
log "=== Project Dependencies ==="

if [ -f pnpm-lock.yaml ]; then
  if [ -d node_modules ]; then
    ok "node_modules (pnpm)"
  else
    miss "node_modules not found (pnpm project)"
    if $FIX; then
      pnpm install --frozen-lockfile 2>&1 | tail -2
      fix "pnpm install completed"
    fi
  fi
elif [ -f package-lock.json ]; then
  if [ -d node_modules ]; then
    ok "node_modules (npm)"
  else
    miss "node_modules not found (npm project)"
    if $FIX; then
      npm ci 2>&1 | tail -2
      fix "npm ci completed"
    fi
  fi
elif [ -f go.mod ]; then
  if [ -f go.sum ] && go mod verify >/dev/null 2>&1; then
    ok "go modules verified"
  else
    miss "go modules incomplete"
    if $FIX; then
      go mod download 2>&1 | tail -2
      fix "go mod download completed"
    fi
  fi
fi

# --- Phase 4: CodeGraph (code knowledge graph) ---
log ""
log "=== CodeGraph ==="

# Check index
if [ -f .codegraph/codegraph.db ]; then
  DB_SIZE=$(du -h .codegraph/codegraph.db | cut -f1 | xargs)
  ok "codegraph.db exists ($DB_SIZE)"
else
  miss "codegraph index not found"
  if $FIX; then
    npx -y @colbymchenry/codegraph init -i 2>&1 | tail -3
    fix "codegraph index built"
  fi
fi

# Check .mcp.json
if [ -f .mcp.json ] && grep -q 'codegraph' .mcp.json 2>/dev/null; then
  ok ".mcp.json has codegraph MCP server"
else
  miss ".mcp.json missing codegraph config"
  if $FIX; then
    if [ -f .mcp.json ]; then
      # Merge codegraph into existing .mcp.json
      python3 -c "
import json
with open('.mcp.json') as f: d = json.load(f)
d.setdefault('mcpServers', {})['codegraph'] = {
  'command': 'npx', 'args': ['-y', '@colbymchenry/codegraph', 'serve', '--mcp']
}
with open('.mcp.json', 'w') as f: json.dump(d, f, indent=2)
" 2>&1
    else
      echo '{"mcpServers":{"codegraph":{"command":"npx","args":["-y","@colbymchenry/codegraph","serve","--mcp"]}}}' | python3 -c "import sys,json; json.dump(json.load(sys.stdin),open('.mcp.json','w'),indent=2)" 2>&1
    fi
    fix ".mcp.json codegraph config added"
  fi
fi

if [ -f .mcp.json ] && grep -q '"lsp-mcp"' .mcp.json 2>/dev/null; then
  miss ".mcp.json has legacy lsp-mcp config (Claude Code should use the LSP plugin; Codex uses ~/.codex/config.toml)"
  if $FIX; then
    remove_legacy_project_lsp_mcp_config ".mcp.json"
    fix "legacy .mcp.json lsp-mcp config removed"
  fi
fi

if [ -f "$CODEX_CONFIG" ] && grep -q '^\[mcp_servers\.codegraph\]' "$CODEX_CONFIG" 2>/dev/null; then
  ok "$CODEX_CONFIG has codegraph MCP server"
else
  miss "$CODEX_CONFIG missing codegraph MCP server"
  if $FIX; then
    if command -v npx >/dev/null; then
      update_codex_codegraph_config "$CODEX_CONFIG"
      fix "Codex codegraph MCP server registered"
    else
      miss "npx not found (needed to run CodeGraph MCP)"
    fi
  fi
fi

ensure_git_info_exclude ".codegraph/" ".mcp.json"

# --- Phase 5: Retrieval rules in CLAUDE.md / AGENTS.md ---
log ""
log "=== Retrieval Rules ==="

HAS_CODEGRAPH=false
[ -f .codegraph/codegraph.db ] && HAS_CODEGRAPH=true

# Build template based on what's installed
if $HAS_CODEGRAPH; then
RETRIEVAL_TEMPLATE='## 代码检索

检索优先级：CodeGraph → LSP → rg → 小范围读文件

**1. CodeGraph（调用链、影响面、符号搜索）**

修改代码前优先用 CodeGraph MCP：
- 查调用关系 → `codegraph_trace` / `codegraph_callers` / `codegraph_callees`
- 评估修改影响 → `codegraph_impact`
- 搜索符号 → `codegraph_search`

一次查询返回完整关系图，替代多轮 rg → 小范围读文件。

**2. LSP（精确符号操作）**

CodeGraph 返回关系后，用 LSP 精确验证：
- `documentSymbol` → 文件结构概览，替代读全文
- `goToDefinition` / `findReferences` → 精确到行的符号定位
- `hover` → 类型签名
- `getDiagnostics` → 快速看当前文件诊断

LSP 冷启动失败后等 3 秒重试一次。不要臆造当前会话里没有暴露的 LSP 工具。

**3. rg（文本搜索）**

路由字符串、配置 key、错误消息、环境变量、非代码文件。

**4. git / 小范围读文件**

- `git` 看状态、分支、提交、diff
- 只精读前面工具定位到的行范围，不读全文'
else
RETRIEVAL_TEMPLATE='## 代码检索

检索优先级：LSP → rg → 小范围读文件

**1. LSP（精确符号操作）**

修改代码前优先用 LSP：
- `documentSymbol` → 文件结构概览，替代读全文
- `goToDefinition` / `findReferences` → 精确到行的符号定位
- `hover` → 类型签名
- `getDiagnostics` → 快速看当前文件诊断

LSP 冷启动失败后等 3 秒重试一次。不要臆造当前会话里没有暴露的 LSP 工具。

**2. rg（文本搜索）**

路由字符串、配置 key、错误消息、环境变量、非代码文件。

**3. git / 小范围读文件**

- `git` 看状态、分支、提交、diff
- 只精读前面工具定位到的行范围，不读全文'
fi

# Check CLAUDE.md. Do not auto-edit tracked team files; local-only Claude notes
# are fine when CLAUDE.md is already ignored or already untracked.
if [ -f CLAUDE.md ] && grep -q '代码检索' CLAUDE.md 2>/dev/null; then
  ok "CLAUDE.md has retrieval rules"
elif [ -f CLAUDE.md ] && git_tracked "CLAUDE.md"; then
  ok "CLAUDE.md is tracked; skip auto-edit"
elif [ ! -f CLAUDE.md ] && ! git_ignored "CLAUDE.md"; then
  ok "CLAUDE.md absent and not ignored (skip local-only edit)"
else
  miss "CLAUDE.md missing retrieval rules"
  if $FIX; then
    { [ -f CLAUDE.md ] && [ -s CLAUDE.md ] && echo ""; echo "$RETRIEVAL_TEMPLATE"; } >> CLAUDE.md
    fix "CLAUDE.md retrieval rules added"
  fi
fi

# Check .codex/AGENTS.md (project-level, not global)
AGENTS_FILE=".codex/AGENTS.md"
if [ -f "$AGENTS_FILE" ] && grep -q '代码检索' "$AGENTS_FILE" 2>/dev/null; then
  ok "$AGENTS_FILE has retrieval rules"
else
  miss "$AGENTS_FILE missing retrieval rules"
  if $FIX; then
    mkdir -p "$(dirname "$AGENTS_FILE")"
    { [ -f "$AGENTS_FILE" ] && [ -s "$AGENTS_FILE" ] && echo ""; echo "$RETRIEVAL_TEMPLATE"; } >> "$AGENTS_FILE"
    fix "$AGENTS_FILE retrieval rules added"
  fi
fi
else
log ""
log "=== Project Dependencies / CodeGraph / Retrieval Rules ==="
ok "skipped (--codex-lsp-only)"
fi

# --- Output ---
echo "$REPORT"

if [ -n "$FIXED" ]; then
  echo "--- Fixed ---"
  echo "$FIXED"
fi

if [ -n "$MISSING" ] && ! $FIX; then
  echo "--- Run with --fix to auto-install missing components ---"
fi
